name: findovio_business
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 0.0.91+4

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  add_2_calendar: ^3.0.1
  animate_gradient: ^0.0.2+1
  animated_gradient: ^0.0.3
  animated_introduction: 
    path: ./plugins/animated_introduction-1.0.4/
  autocomplete_textfield: ^2.0.1
  blurrycontainer: ^2.1.0
  bubble: ^1.2.1
  cached_network_image: ^3.3.1
  calendar_view: ^1.1.0
  cloud_firestore: ^4.17.3
  connectivity_plus: ^6.0.3
  debounce_throttle: ^2.0.0
  dotted_border: ^2.1.0
  dropdown_button2: ^2.3.9
  dropdown_plus_plus: ^0.1.1+1
  dropdown_search: ^5.0.6
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  firebase_messaging: ^14.9.4
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.2
  flutter_chat_ui: ^1.6.13
  flutter_firebase_chat_core: ^1.6.7
  flutter_html: ^3.0.0-alpha.3
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_signin_button: ^2.0.0
  flutter_svg: ^2.0.10+1
  flutter_typeahead: ^5.2.0
  get: ^4.6.6
  google_sign_in: ^6.2.1
  gradient_borders: ^1.0.0
  http: ^1.2.1
  http_parser: ^4.0.2
  image: ^4.1.7
  image_picker: ^1.0.7
  intl: ^0.18.1
  linear_progress_bar: ^1.1.1
  material_design_icons_flutter: ^7.0.7296
  numberpicker: ^2.1.2
  passwordfield: ^0.2.0
  path_provider: ^2.1.3
  persistent_bottom_nav_bar: ^5.0.2
  persistent_bottom_nav_bar_v2: ^5.0.0
  phone_input: ^1.0.0
  provider: ^6.1.2
  scrollable_positioned_list: ^0.3.8
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  table_calendar: ^3.0.9
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: BioRhyme
      fonts:
        - asset: assets/fonts/BioRhyme/BioRhyme-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/BioRhyme/BioRhyme-Light.ttf
          weight: 300
        - asset: assets/fonts/BioRhyme/BioRhyme-Regular.ttf
          weight: 400
        - asset: assets/fonts/BioRhyme/BioRhyme-Medium.ttf
          weight: 500
        - asset: assets/fonts/BioRhyme/BioRhyme-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/BioRhyme/BioRhyme-Bold.ttf
          weight: 700
        - asset: assets/fonts/BioRhyme/BioRhyme-ExtraBold.ttf
          weight: 800

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/grads/
    - assets/images/gifs/

flutter_native_splash:
  color: "#ffffff" # Kolor tła splash screena (może być w formacie HEX lub nazwie koloru)
  image: assets/images/splash.png # Ścieżka do obrazu używanego jako splash screen
  android: true # Włączanie splash screena dla Androida
  ios: true # Włączanie splash screena dla iOS
  web: true # Włączanie splash screena dla web (opcjonalnie)
  fullscreen: true # Ustawienie splash screena na pełny ekran



