// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtXkpvSv8helmcQiPmjggrYMLtUesYNF4',
    appId: '1:722157186371:web:f0dfde74d5197aefa6d3f6',
    messagingSenderId: '722157186371',
    projectId: 'findoviobusiness',
    authDomain: 'findoviobusiness.firebaseapp.com',
    storageBucket: 'findoviobusiness.appspot.com',
    measurementId: 'G-SH6Y5K8YZ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwFxQlfhZdeNOin9KdbnfeOdZdvSFB5MM',
    appId: '1:722157186371:android:4d41f2dbb5fca6e0a6d3f6',
    messagingSenderId: '722157186371',
    projectId: 'findoviobusiness',
    storageBucket: 'findoviobusiness.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZvfgA-hBX-0uiCJRvV9pkoHk8pqa_62s',
    appId: '1:722157186371:ios:85db27c7a3e37077a6d3f6',
    messagingSenderId: '722157186371',
    projectId: 'findoviobusiness',
    storageBucket: 'findoviobusiness.appspot.com',
    iosBundleId: 'com.example.findovioBusiness',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZvfgA-hBX-0uiCJRvV9pkoHk8pqa_62s',
    appId: '1:722157186371:ios:8f721d0594586471a6d3f6',
    messagingSenderId: '722157186371',
    projectId: 'findoviobusiness',
    storageBucket: 'findoviobusiness.appspot.com',
    iosBundleId: 'com.example.findovioBusiness.RunnerTests',
  );
}
